repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.1.1
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: ['build','chore','ci','docs','feat','fix','perf','refactor','revert','style','test']

- repo: 'https://github.com/pycqa/isort'
  rev: '5.12.0'
  hooks:
  - id: isort
    name: Sort Imports

- repo: 'https://github.com/pre-commit/mirrors-mypy'
  rev: v0.931
  hooks:
  - id: mypy
    name: Type Check
    exclude: 'tests/.*'

- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: v3.2.0
  hooks:
  - id: requirements-txt-fixer

- repo: 'https://github.com/psf/black'
  rev: '22.12.0'
  hooks:
  - id: black
    name: Format Code

- repo: 'https://github.com/charliermarsh/ruff-pre-commit'
  rev: v0.0.261
  hooks:
  - id: ruff
    name: Code Quality
    args: ['--fix']

- repo: 'https://github.com/econchick/interrogate'
  rev: '1.5.0'
  hooks:
  - id: interrogate
    name: Check Docstrings
    pass_filenames: false

- repo: local
  hooks:
  - id: unittest
    name: Run Unit Tests
    entry: python3 -B -m coverage run -m unittest discover docbr
    language: python
    types: [python]
    pass_filenames: false
  - id: coverage
    name: Coverage Report
    entry: python3 -B -m coverage report
    language: python
    types: [python]
    args: ['--fail-under=90']
    pass_filenames: false